CI: Remove testing against CrateDB 4.8, it fails building on GHA
This, in turn, makes the whole CrateDB nightly build pipeline go south,
effectively stopping publishing of nightly OCI images.

  fatal error in thread [main], exiting
  java.lang.ExceptionInInitializerError: null

  NullPointerException: Cannot invoke
  "jdk.internal.platform.CgroupInfo.getMountPoint()" because
  "anyController" is null